### ISSUE TITLE
Boot from undeploy, VM Running bu monitor state is Poweroff

### ISSUE THREAD

**Issue by feldsam** [OpenNebula/one#6153]
**Description**
When I start VM from UNDEPLOYED state, VM started successfully, reported RUNNING state, but few seconds after, state is changed to POWEROFF because of monitoring drives thinks different.

**To Reproduce**
This not happens always, just from time to time, probably when BOOT_UNDEPLOY hit monitoring cycle?
Undeploy VM, them start it and wait.

**Expected behavior**
Keep RUNNING state of VM

**Details**
 - Affected Component: [Monitor]
 - Hypervisor: [KVM]
 - Version: [6.2]

**Additional context**
VM log:
```
Sat Mar 11 22:06:50 2023 [Z0][VM][I]: New LCM state is EPILOG_UNDEPLOY
Sat Mar 11 22:06:59 2023 [Z0][VM][I]: New state is UNDEPLOYED
Sat Mar 11 22:06:59 2023 [Z0][VM][I]: New LCM state is LCM_INIT
Sun Mar 12 07:29:41 2023 [Z0][VM][I]: New state is PENDING
Sun Mar 12 07:29:53 2023 [Z0][VM][I]: New state is ACTIVE
Sun Mar 12 07:29:53 2023 [Z0][VM][I]: New LCM state is PROLOG_UNDEPLOY
Sun Mar 12 07:30:18 2023 [Z0][VM][I]: New LCM state is BOOT_UNDEPLOY
Sun Mar 12 07:30:18 2023 [Z0][VMM][I]: Generating deployment file: /var/lib/one/vms/10411/deployment.10
Sun Mar 12 07:30:18 2023 [Z0][VMM][I]: Successfully execute transfer manager driver operation: tm_context.
Sun Mar 12 07:30:19 2023 [Z0][VMM][I]: ExitCode: 0
Sun Mar 12 07:30:19 2023 [Z0][VMM][I]: Successfully execute network driver operation: pre.
Sun Mar 12 07:30:19 2023 [Z0][VMM][I]: Successfully execute virtualization driver operation: /bin/mkdir -p.
Sun Mar 12 07:30:19 2023 [Z0][VMM][I]: Successfully execute virtualization driver operation: /bin/cat - >/var/lib/one/vms/10411/vm.xml.
Sun Mar 12 07:30:19 2023 [Z0][VMM][I]: Successfully execute virtualization driver operation: /bin/cat - >/var/lib/one/vms/10411/ds.xml.
Sun Mar 12 07:30:22 2023 [Z0][VMM][I]: Successfully execute virtualization driver operation: deploy.
Sun Mar 12 07:30:25 2023 [Z0][VMM][I]: post: Running /var/tmp/one/vnm/802.1Q/post.d/vnfilter_post
Sun Mar 12 07:30:25 2023 [Z0][VMM][I]: post:
Sun Mar 12 07:30:25 2023 [Z0][VMM][I]: ExitCode: 0
Sun Mar 12 07:30:25 2023 [Z0][VMM][I]: Successfully execute network driver operation: post.
Sun Mar 12 07:30:25 2023 [Z0][LCM][I]: VM reported RUNNING by the drivers
Sun Mar 12 07:30:25 2023 [Z0][VM][I]: New LCM state is RUNNING
Sun Mar 12 07:30:30 2023 [Z0][LCM][I]: VM running but monitor state is POWEROFF
Sun Mar 12 07:30:30 2023 [Z0][VM][I]: New LCM state is SHUTDOWN_POWEROFF
Sun Mar 12 07:30:30 2023 [Z0][VM][I]: New state is POWEROFF
```

UPDATE:
Adding logs when I keep VM in fake POWEROFF state and it is found again by drivers:
```
Mon Mar 13 09:26:43 2023 [Z0][VM][I]: New LCM state is RUNNING
Mon Mar 13 09:26:51 2023 [Z0][LCM][I]: VM running but monitor state is POWEROFF
Mon Mar 13 09:26:51 2023 [Z0][VM][I]: New LCM state is SHUTDOWN_POWEROFF
Mon Mar 13 09:26:51 2023 [Z0][VM][I]: New state is POWEROFF
Mon Mar 13 09:26:51 2023 [Z0][VM][I]: New LCM state is LCM_INIT
Mon Mar 13 09:29:57 2023 [Z0][VMM][I]: VM found again by the drivers
Mon Mar 13 09:29:57 2023 [Z0][VM][I]: New state is ACTIVE
Mon Mar 13 09:29:57 2023 [Z0][VM][I]: New LCM state is RUNNING
```

## Progress Status
- [ ] Code committed
- [ ] Testing - QA
- [ ] Documentation (Release notes - resolved issues, compatibility, known issues)

**Comment by paczerny** [comment]
@feldsam What's your OpenNebula version? 

I wasn't able to reproduce. There was an issue in the monitoring sync state (#5581), fixed in 6.2.1 EE release.

**Comment by feldsam** [comment]
Hello @paczerny, I am on 6.2.2 and when I look into code, them patch from 5581 is applied.

**Comment by paczerny** [comment]
I'm not able to reproduce in 6.4+
The 6.2 version is no longer supported. Closing for now. If you are able to reproduce in OpenNebula version 6.4+, feel free to reopen the issue

**Comment by feldsam** [comment]
Hello @paczerny , I hit this issue regullary and it is not related to boot from updeploy. For example today it happens because VM was longer time in pending state and after boot it agains show messages about monitor state is poweroff. Would you please point me to some commits related to this in 6.4? Thanks!

**Comment by feldsam** [comment]
Hello @paczerny @dann1 , looks like this is not fixed, see report from other user usign 6.4 CE https://github.com/OpenNebula/one/issues/3426#issuecomment-1403622295

I also checked probe_db.rb file, and it is same as we have deployed, no new changes

https://github.com/OpenNebula/one/commits/master/src/im_mad/remotes/lib/probe_db.rb
